defaults:
  - common
  - _self_

agent:
  _target_: planseqlearn.agents.drqv2RGBM.DrQV2RGBMAgent
  use_pool_encoder: false
  pool_encoder_latent_dim: 512 # Only used if use_pool_encoder is set to true

use_rgbm: true
add_segmentation_to_obs: true
