defaults:
  - common
  - _self_

agent:
  _target_: planseqlearn.agents.drqv2AE.DrQV2AEAgent
  reconstruction_loss_coeff: 2 # Controls balance between critic and decoder on encoder gradient updates
  decoder_lr: 1e-4
  latent_dim: ${latent_dim}
  detach_critic: false # Prevent critic loss from backpropagating through encoder
  detach_decoders: false # Prevent decoder losses from backpropagating through encoder

add_segmentation_to_obs: false
latent_dim: 4096
