defaults:
  - common
  - _self_

agent:
  _target_: planseqlearn.agents.V1_random_mask.V1RandomMaskAgent
  reconstruction_loss_coeff: 1 # Controls balance between critic and decoder on encoder gradient updates
  decoder_lr: 1e-4
  mask_lr: 1e-4
  mask_loss_coeff: 2.5e-1
  latent_dim: ${latent_dim}
  detach_critic: false # Prevent critic loss from backpropagating through encoder
  detach_decoders: false # Prevent decoder losses from backpropagating through encoder
  num_patches: 100
  patch_size: 3

add_segmentation_to_obs: false
latent_dim: 4096
