defaults:
  - common
  - _self_

agent:
  _target_: planseqlearn.agents.V2.V2Agent
  mask_lr: 1e-4
  mask_loss_coeff: 2.5e-1
  latent_dim: ${latent_dim}

add_segmentation_to_obs: true
latent_dim: 4096
