defaults:
  - common
  - _self_

agent:
  _target_: planseqlearn.agents.V4.V4Agent
  reconstruction_loss_coeff: 1 # Controls balance between critic and decoder on encoder gradient updates
  decoder_lr: 1e-4
  mask_lr: 1e-4
  mask_loss_coeff: 2.5e-1
  detach_critic: false # Prevent critic loss from backpropagating through encoder
  detach_decoders: false # Prevent decoder losses from backpropagating through encoder

add_segmentation_to_obs: true
